feats = {"29_10_23_nonparam" : [['bjet1_bID_deepFlavor',
                    'bjet2_cID_deepFlavor',
                    'bjet1_HHbtag',
                    'bjet2_HHbtag',
                    'bjet1_cID_deepFlavor',
                    'dR_b1_b2',
                    'dau1_mt',
                    'dau2_pt',
                    'll_mt',
                    'dR_l1_l2_x_sv_pt',
                    'dR_l1_l2',
                    'deta_l1_l2',
                    'sv_E',
                    'sv_mt',
                    'sv_mass',
                    'met_pt',
                    'h_bb_mass',
                    'hh_pt',
                    'HHKin_mass_raw',
                    'HHKin_mass_raw_chi2',
                    'dphi_hbb_met',
                    'deta_hbb_httvis',
                    'diH_mass_met'],
                    ['boosted', 'pairType', 'is_vbf']],
    "nonparam_baseline" : [['sv_mt', 'met_pt', 'dR_b1_b2', 'sv_E',
                                  'bjet1_HHbtag', 'll_mt', 'sv_mass', 'dR_l1_l2_x_sv_pt', 'dau2_pt',
                                  'dau1_mt', 'HHKin_mass_raw_chi2', 'h_bb_mass', 'top_1_mass',
                                  'hh_pt', 'dphi_hbb_met', 'deta_l1_l2', 'bjet1_cID_deepFlavor',
                                  'bjet1_cID_deepFlavor'],
                                ['isBoosted', 'pairType', 'has_vbf_pair']],
          "param_baseline" : [['sv_mt',
                               'met_pt',
                               'dR_b1_b2',
                               'sv_E',
                               'bjet1_HHbtag',
                               'll_mt',
                               'sv_mass',
                               'dR_l1_l2_x_sv_pt',
                               'dau2_pt',
                               'dau1_mt',
                               'HHKin_mass_raw_chi2',
                               'h_bb_mass',
                               'top_1_mass',
                               'hh_pt',
                               'dphi_hbb_met',
                               'deta_l1_l2',
                               'res_mass',
                               'bjet1_CvsB',
                               'bjet2_CvsB',
                               'bjet1_CvsL'],
                              ['isBoosted', 'pairType', 'has_vbf_pair', 'spin']],
          "nonparam_SR" : [['bjet1_bID_deepFlavor',
                            'bjet2_cID_deepFlavor',
                            'bjet1_HHbtag',
                            'bjet2_HHbtag',
                            'bjet1_cID_deepFlavor',
                            'dR_b1_b2',
                            'dau1_mt',
                            'dau2_pt',
                            'll_mt',
                            'dR_l1_l2_x_sv_pt',
                            'dR_l1_l2',
                            'deta_l1_l2',
                            'sv_E',
                            'sv_mt',
                            'sv_mass',
                            'met_pt',
                            'top_1_mass',
                            'h_bb_mass',
                            'hh_pt',
                            'HHKin_mass_raw_chi2',
                            'dphi_hbb_met',
                            'deta_hbb_httvis',
                            'HHKin_mass_raw',
                            'diH_mass_met'],
                            ['isBoosted', 'pairType', 'has_vbf_pair']],
          "combined_model_nograd" : [['bjet1_bID_deepFlavor',
                            'bjet2_cID_deepFlavor',
                            'bjet1_HHbtag',
                            'bjet2_HHbtag',
                            'bjet1_cID_deepFlavor',
                            'dR_b1_b2',
                            'dau1_mt',
                            'dau2_pt',
                            'll_mt',
                            'dR_l1_l2_x_sv_pt',
                            'dR_l1_l2',
                            'deta_l1_l2',
                            'sv_E',
                            'sv_mt',
                            'sv_mass',
                            'met_pt',
                            'top_1_mass',
                            'h_bb_mass',
                            'hh_pt',
                            'HHKin_mass_raw_chi2',
                            'dphi_hbb_met',
                            'deta_hbb_httvis',
                            'HHKin_mass_raw',
                            'diH_mass_met'],
                            ['isBoosted', 'pairType', 'has_vbf_pair']],
          "param_SR" : [['bjet1_bID_deepFlavor',
                            'bjet2_cID_deepFlavor',
                            'bjet1_HHbtag',
                            'bjet2_HHbtag',
                            'bjet1_cID_deepFlavor',
                            'dR_b1_b2',
                            'dau1_mt',
                            'dau2_pt',
                            'll_mt',
                            'dR_l1_l2_x_sv_pt',
                            'dR_l1_l2',
                            'deta_l1_l2',
                            'sv_E',
                            'sv_mt',
                            'sv_mass',
                            'met_pt',
                            'top_1_mass',
                            'h_bb_mass',
                            'hh_pt',
                            'HHKin_mass_raw_chi2',
                            'dphi_hbb_met',
                            'deta_hbb_httvis',
                            'HHKin_mass_raw',
                            'diH_mass_met',
                            'res_mass',
                            'spin'],
                            ['isBoosted', 'pairType', 'has_vbf_pair']],
          "nonparam_htautau" : [['bjet1_bID_deepFlavor', 'bjet2_cID_deepFlavor', 'bjet1_HHbtag', 'bjet2_HHbtag', 'bjet1_cID_deepFlavor',
                                'dR_b1_b2', 'dau1_mt', 'dau2_pt', 'll_mt', 'dR_l1_l2_x_sv_pt', 'dR_l1_l2', 'deta_l1_l2', 'sv_E', 'sv_mt', 'sv_mass', 'met_pt',
                                'top_1_mass', 'h_bb_mass', 'hh_pt', 'HHKin_mass_raw_chi2', 'dphi_hbb_met', 'deta_hbb_httvis',
                                'tautau_cls_0', 'tautau_cls_1', 'tautau_cls_2',
                                'tautau_reg_0', 'tautau_reg_1', 'tautau_reg_2', 'tautau_reg_3', 'tautau_reg_4', 'tautau_reg_5',
                                'tautau_cstm_0', 'tautau_cstm_1', 'tautau_cstm_2', 'tautau_cstm_3', 'tautau_cstm_4', 'tautau_cstm_5', 'tautau_cstm_6'],
                                ['isBoosted', 'pairType', 'has_vbf_pair']],
          "nmc" : [['sv_mt', 'met_pt', 'dR_b1_b2', 'sv_E', 'bjet1_HHbtag', 'll_mt',
                    'sv_mass', 'dR_l1_l2_x_sv_pt', 'dau1_pt', 'dau1_mt', 'HHKin_mass_raw_chi2',
                    'h_bb_mass', 'top_1_mass', 'hh_pt', 'dphi_hbb_met', 'deta_l1_l2', 'b_1_cvsb',
                    'b_2_cvsb', 'b_1_cvsl',],
                  ['isBoosted', 'pairType', 'has_vbf_pair', 'jet_1_quality', 'jet_2_quality', 'spin']],
          "nmc_cont_feats_param" : [['HHKin_mass_raw_chi2', 'sv_mass', 'dau2_pt', 'res_mass', 'dau1_mt', 'dR_l1_l2_x_sv_pt', 'h_bb_mass',
                                  'diH_mass_met', 'dR_l1_l2', 'HHKin_mass_raw', 'deta_hbb_httvis', 'bjet2_HHbtag', 'sv_mt', 'b_1_cvsl',
                                  'b_1_cvsb', 'b_2_cvsb'],
                                  ['isBoosted', 'pairType', 'has_vbf_pair', 'jet_1_quality', 'jet_2_quality', 'spin', 'year']]
}